### ISSUE TITLE
Support BED instead of MetH5 as input format?

### ISSUE THREAD

**Issue by PanZiwei** [snajder-r/pycoMeth#7]
Hi,
I am interested in using `Meth_Comp` for DMR analysis and I already have per-site methylation calling results for 2 samples, they are in BED format with chromosome, start position, end position, and methylation frequency for each site. 

Is it possible to use BED file instead of MetH5 in this case? Any hints for the implementation? Thanks.

**Comment by snajder-r** [comment]
Hi!

PycoMeth is designed to work on read-level methylation calls and consider each methylation calls confidence level. 

What you have, if I understand you correctly, is already reduced to a per-site frequency. PycoMeth is not designed to work on this level of data. I'd refer you to tools such as the R package methylKit (which we used as a benchmark in the paper), since that works on the sort of data you have.

I'm closing this issue as it is out-of-scope for pycoMeth :-)
